<?php
/**
 * @file
 * Code for the Service Learning feature.
 */

include_once 'asu_usl_internships.features.inc';

/**
 * Implements hook_cron()
 * Performs repetitive functions at set intervals or when called manually
 */
function asu_usl_internships_cron() {
  asu_usl_internships_expire_spas();
}

/**
 * Automatically expires Student Placement Agreements approved 5 years ago or more
 */
function asu_usl_internships_expire_spas() {
  // 5 years as Unix timestamp
  $year = 31570560;
  
  // Get all nodes that were approved by SPA more than five years ago
  $nodes = db_select('workbench_moderation_node_history', 'h')
    ->fields('h')
    ->condition('state', 'spa_approved', '=')
    ->condition('stamp', time()-($year*5), '<=')
    ->execute()
    ->fetchAll();
  
  // Get all nodes that are already expired
  $expnodes = db_select('workbench_moderation_node_history', 'h')
    ->fields('h')
    ->condition('state', 'expired', '=')
    ->execute()
    ->fetchAll();
    
  // Expire nodes older than 
  foreach($nodes as $db_node) {
    $node = node_load($db_node->nid);
    $found = false;
    foreach($expnodes as $expnode){
      if($expnode->nid == $node->nid){
        $found = true;
      }
    }
    if(!$found){
      workbench_moderation_moderate($node, 'expired');
    }
  }
}